variables:
  DARKPAN_REPO_URL: "http://ib-dev-mojo-darkpan.int.kn:8080/publish"

stages:
  - configure
  - dist
  - check
  - publish
  - cleanup

configure:
  stage: configure
  before_script:
   - export HTTPS_PROXY=http://kn.proxy.int.kn:80
   - cpm  install  --test --with-configure --without-test --without-develop --without-runtime --local-lib-contained ./local
  script:
    - export BUILD_NUMBER="$CI_PIPELINE_ID"
    - perl Makefile.PL verbose
  rules:
  - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "development"'

dist:
  stage: dist
  script:
    - make dist
  artifacts:
    paths:
      - '*.tar.gz'
  variables:
    GIT_STRATEGY: "none"
  rules:
  - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "development"'

check_artifact:
  stage: check
  variables:
    GIT_STRATEGY: "none"
  script:
    - perl -Mstrict -Mwarnings -E '
        my @distName = glob( q(*.tar.gz) );
        die "Zero or more than one .tar.gz file found!\n" unless @distName == 1;
        say "DIST_NAME=$distName[0]"
      ' > variables.env
  artifacts:
    reports:
      dotenv: variables.env
  rules:
  - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "development"'

publish:
  stage: publish
  variables:
    GIT_STRATEGY: "none"
  rules:
  - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "development"'
  script: |
    #!/bin/bash
    
    # Extract the email address
    # Get the local part of the email (before @)
    # Split the local part into first name and second name
    # Convert to uppercase
    # Take first 2 characters of the first name
    # Concatenate and print
    artificialPauseId=$(
      perl -Mstrict -Mwarnings -e '
        my ( $first, $second ) = map { uc } ( $ARGV[0] =~ m/ < ([^.@]+) \. ([^.@]+) /x );
        print substr( $first, 0, 2 ), $second
      ' "$CI_COMMIT_AUTHOR"
    )

    # Traced publish call to DarkPAN web server
    set -x 
    curl -s -F "author=$artificialPauseId" -F "pause99_add_uri_httpupload=@$DIST_NAME" $DARKPAN_REPO_URL

cleanup:
  stage: cleanup
  script:
    - rm -f variables.env
  when: always
